version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: my_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      #  - ./Base/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  apache:
    image: httpd:latest
    container_name: my-apache-app
      # ports:
      #- '8082:80'
    volumes:
      - ./web_proj/:/usr/local/apache2/htdocs
    networks:
      - app_network

  app:
    build: ./python_app
    restart: always
    container_name: python_app
      # ports:
      # - '8083:8000'
    environment:
      DB_HOST: my_pg
      DB_PORT: 5432
      DB_NAME: my_database
      DB_USER: postgres
      DB_PASSWORD: 'password'
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - app_network

networks:
  app_network:
   driver: bridge
#volumes:
#db_data:
